"""Initial migration

Revision ID: 1f2a62932248
Revises: 
Create Date: 2026-04-01 00:26:43.386136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2a62932248'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('stream', sa.String(length=60), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('nirf_rank', sa.Integer(), nullable=True),
    sa.Column('fees_per_year', sa.Float(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('trends', sa.JSON(), nullable=True),
    sa.Column('avg_ctc', sa.Float(), nullable=True),
    sa.Column('highest_ctc', sa.Float(), nullable=True),
    sa.Column('placement_pct', sa.Float(), nullable=True),
    sa.Column('top_recruiters', sa.JSON(), nullable=True),
    sa.Column('established', sa.Integer(), nullable=True),
    sa.Column('accreditation', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('stream', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('colleges')
    # ### end Alembic commands ###
